// app/api/common/permissions-map.js
export const PERMISSIONS = {
  // Authentication & Profile (All roles)
  "auth:login": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "profile:read": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "profile:update": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],

  // Employee Base Permissions
  "news:read": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "schedule:read": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "report:create": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "leave:create": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "profile:manage": [
    "employee",
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],

  // Event Organizer Permissions
  "service_order:read": ["event_organizer", "senior_manager", "system_admin"],
  "service_order:create": ["event_organizer", "senior_manager", "system_admin"],
  "service_order:update": ["event_organizer", "senior_manager", "system_admin"],
  "service_order:delete": ["event_organizer", "senior_manager", "system_admin"],
  "event_plan:create": ["event_organizer", "senior_manager", "system_admin"],
  "task:assign": ["event_organizer", "senior_manager", "system_admin"],
  "hr:read": ["event_organizer", "senior_manager", "system_admin"],
  "hr:update": ["event_organizer", "senior_manager", "system_admin"],
  "hr:delete": ["event_organizer", "senior_manager", "system_admin"],
  "service:read": [
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "service:update": [
    "event_organizer",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "service:delete": ["event_organizer", "senior_manager", "system_admin"],
  "blog:create": [
    "event_organizer",
    "marketing",
    "senior_manager",
    "system_admin",
  ],
  "blog:read": [
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "blog:update": [
    "event_organizer",
    "marketing",
    "senior_manager",
    "system_admin",
  ],
  "contract:read": ["event_organizer", "senior_manager", "system_admin"],
  "contract:create": ["event_organizer", "senior_manager", "system_admin"],
  "contract:update": ["event_organizer", "senior_manager", "system_admin"],
  "contract:delete": ["event_organizer", "senior_manager", "system_admin"],
  "equipment:create": ["event_organizer", "senior_manager", "system_admin"],
  "equipment:read": [
    "event_organizer",
    "event_execution",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "equipment:update": ["event_organizer", "senior_manager", "system_admin"],
  "equipment:delete": ["event_organizer", "senior_manager", "system_admin"],

  // Event Execution Permissions
  "service_plan:read": [
    "event_execution",
    "event_organizer",
    "senior_manager",
    "system_admin",
  ],
  "progress:report": [
    "event_execution",
    "event_organizer",
    "senior_manager",
    "system_admin",
  ],
  "chat:access": [
    "event_execution",
    "event_organizer",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "plan:propose": [
    "event_execution",
    "event_organizer",
    "senior_manager",
    "system_admin",
  ],

  // Senior Manager Permissions
  "leave:read_all": ["senior_manager", "system_admin"],
  "leave:approve": ["senior_manager", "system_admin"],
  "leave:reject": ["senior_manager", "system_admin"],
  "service:approve": ["senior_manager", "system_admin"],
  "blog:approve": ["senior_manager", "system_admin"],
  "blog:delete": ["senior_manager", "system_admin"],
  "event_plan:read": [
    "event_execution",
    "event_organizer",
    "senior_manager",
    "system_admin",
  ],
  "event_plan:approve": ["senior_manager", "system_admin"],
  "event_plan:delete": ["senior_manager", "system_admin"],
  "promotion:read": ["senior_manager", "marketing", "system_admin"],
  "promotion:approve": ["senior_manager", "system_admin"],
  "promotion:delete": ["senior_manager", "system_admin"],
  "event:read": [
    "event_execution",
    "event_organizer",
    "senior_manager",
    "marketing",
    "system_admin",
  ],
  "event:approve": ["senior_manager", "system_admin"],
  "event:delete": ["senior_manager", "system_admin"],

  // Marketing Staff Permissions
  "service:create": [
    "marketing",
    "event_organizer",
    "senior_manager",
    "system_admin",
  ],
  "promotion:create": ["marketing", "senior_manager", "system_admin"],
  "promotion:update": ["marketing", "senior_manager", "system_admin"],
  "event:create": [
    "marketing",
    "event_organizer",
    "senior_manager",
    "system_admin",
  ],
  "event:update": [
    "marketing",
    "event_organizer",
    "senior_manager",
    "system_admin",
  ],

  // System Admin Permissions
  "user:read": ["system_admin"],
  "user:create": ["system_admin"],
  "user:update": ["system_admin"],
  "user:delete": ["system_admin"],
  "system:manage": ["system_admin"],
  "report:read": ["senior_manager", "system_admin"],
  "report:update": ["senior_manager", "system_admin"],
  "report:delete": ["senior_manager", "system_admin"],
};
